version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - QDRANT_HOST=host.docker.internal
      - QDRANT_PORT=6333
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - type: bind
        source: ./data
        target: /app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"